#!/bin/sh

case "$1" in
    start)
        echo "Starting aesdsocket server"
        start-stop-daemon -S -x /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping aesdsocket server"
        killall -TERM aesdsocket
        #start-stop-daemon --stop aesdsocket
        ;;
    status)
        if pgrep -f aesdsocket &> /dev/null ; then
            echo "aesdsocket is running"
        else
            echo "aesdsocket is not running"
        fi
        ;;
    *)
        echo "Usage $0 [start|stop|status]"
        exit 1
        ;;
esac
